/* The local machine's resolver configuration: /etc/hosts and /etc/resolv.conf.
 *
 * Both are real files in the virtual filesystem — edit them with the Text
 * Editor (or `sudo tee`, or the browser's about:dns page) and the resolver
 * picks the change up immediately.
 */
import { vfs } from '../../os/vfs'
import { NAMESERVERS } from '../dns'

export const HOSTS_PATH = '/etc/hosts'
export const RESOLV_CONF_PATH = '/etc/resolv.conf'

export const DEFAULT_HOSTS = `# /etc/hosts — static table lookup for hostnames.
# Entries here are checked before MixtNet DNS, exactly like a real resolver.
127.0.0.1       localhost
127.0.1.1       mixt-web
::1             localhost ip6-localhost ip6-loopback
10.0.0.53       ns1.mixtnet.com dns1
10.0.0.54       ns2.mixtnet.com dns2

# Add your own names below, e.g.
# 10.99.0.1     my-server.lan
`

export const DEFAULT_RESOLV_CONF = `# Generated by MixtNet NetworkManager.
${NAMESERVERS.map((ns) => `nameserver ${ns === 'ns1.mixtnet.com' ? '10.0.0.53' : '10.0.0.54'}`).join('\n')}
search mixtnet
options timeout:1 attempts:2
`

/** `hostname → address`, exactly how a resolver reads the file. */
export function parseHosts(text: string): Map<string, string> {
  const table = new Map<string, string>()
  for (const raw of (text ?? '').split('\n')) {
    const line = raw.split('#')[0].trim()
    if (!line) continue
    const parts = line.split(/\s+/)
    const ip = parts.shift()
    if (!ip) continue
    for (const name of parts) table.set(name.toLowerCase(), ip)
  }
  return table
}

/** The hosts file as the resolver sees it right now (never throws). */
export function readHostsFile(): string {
  try {
    return vfs.read(HOSTS_PATH) ?? DEFAULT_HOSTS
  } catch {
    return DEFAULT_HOSTS
  }
}

export function readHosts(): Map<string, string> {
  return parseHosts(readHostsFile())
}

export function writeHostsFile(text: string) {
  vfs.write(HOSTS_PATH, text.endsWith('\n') ? text : `${text}\n`, 'text/plain')
}

/** Adds (or replaces) a name → address pair. Returns the new file contents. */
export function addHostEntry(name: string, ip: string): string {
  const host = name.trim().toLowerCase()
  const address = ip.trim()
  const lines = readHostsFile().split('\n')
  const filtered = lines.filter((line) => {
    const parts = line.split('#')[0].trim().split(/\s+/)
    return !parts.slice(1).map((p) => p.toLowerCase()).includes(host)
  })
  // keep the comment tail at the bottom
  const firstComment = filtered.findIndex((line) => line.trim().startsWith('#'))
  const head = firstComment === -1 ? filtered : filtered.slice(0, firstComment)
  const tail = firstComment === -1 ? [] : filtered.slice(firstComment)
  const text = [...head.filter((l) => l.trim() !== ''), `${address.padEnd(15)} ${host}`, '', ...tail].join('\n')
  writeHostsFile(text)
  return text
}

export function removeHostEntry(name: string): string {
  const host = name.trim().toLowerCase()
  const lines = readHostsFile()
    .split('\n')
    .filter((line) => !line.split('#')[0].trim().split(/\s+/).slice(1).map((p) => p.toLowerCase()).includes(host))
  const text = lines.join('\n')
  writeHostsFile(text)
  return text
}

export function readResolvConf(): { nameservers: string[]; search: string[] } {
  const nameservers: string[] = []
  const search: string[] = []
  for (const raw of readHostsFileSafe(RESOLV_CONF_PATH).split('\n')) {
    const line = raw.split('#')[0].trim()
    if (line.startsWith('nameserver')) nameservers.push(line.split(/\s+/)[1])
    if (line.startsWith('search')) search.push(...line.split(/\s+/).slice(1))
  }
  return { nameservers, search }
}

function readHostsFileSafe(path: string) {
  try {
    return vfs.read(path) ?? ''
  } catch {
    return ''
  }
}

/** Called at boot: make sure the resolver files exist and point at MixtNet. */
export function ensureNetworkFiles() {
  if (!vfs.exists(HOSTS_PATH)) writeHostsFile(DEFAULT_HOSTS)
  const resolv = readHostsFileSafe(RESOLV_CONF_PATH)
  if (!resolv || /1\.1\.1\.1|9\.9\.9\.9/.test(resolv)) {
    vfs.write(RESOLV_CONF_PATH, DEFAULT_RESOLV_CONF, 'text/plain')
  }
}
