/* Generated by scripts/gen-appindex.mjs from src/apps — do not edit by hand.
 *
 * One record per application: its name, a one-line summary, the description
 * shown in the menu and the store, the file that implements it, and every
 * module that file imports. `src/os/appindex.ts` is read by the desktop to lay
 * out /usr/share/applications, so the filesystem and the code agree.
 */
export interface AppIndexEntry {
  id: string
  name: string
  summary: string
  description: string
  file: string
  categories: string[]
  keywords: string[]
  dependencies: string[]
}

export const APP_INDEX: AppIndexEntry[] = [
  {
    "id": "nemo",
    "name": "Files",
    "summary": "File Manager",
    "description": "Browse the files and folders on this computer",
    "file": "src/apps/files.tsx",
    "categories": [
      "Accessories",
      "System"
    ],
    "keywords": [
      "nemo",
      "explorer",
      "folder",
      "documents",
      "trash"
    ],
    "dependencies": [
      "react",
      "src/apps/registry.tsx",
      "src/os/bus.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx",
      "src/shell/ContextMenu.tsx"
    ]
  },
  {
    "id": "terminal",
    "name": "Terminal",
    "summary": "Terminal Emulator",
    "description": "Run commands, scripts and system tools",
    "file": "src/apps/terminal.tsx",
    "categories": [
      "Accessories",
      "System"
    ],
    "keywords": [
      "bash",
      "shell",
      "console",
      "command",
      "mixt-terminal"
    ],
    "dependencies": [
      "react",
      "src/apps/registry.tsx",
      "src/net/index.tsx",
      "src/os/bus.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/users.ts",
      "src/os/vfs.ts"
    ]
  },
  {
    "id": "browser",
    "name": "Mixtsfox",
    "summary": "Web Browser",
    "description": "Browse MixtNet or the wider web — tabs, bookmarks, Mixtsfox Search",
    "file": "src/apps/browser.tsx",
    "categories": [
      "Internet"
    ],
    "keywords": [
      "browser",
      "mixtsfox",
      "mixtnet",
      "web",
      "internet",
      "surf"
    ],
    "dependencies": [
      "react",
      "src/net/downloads.ts",
      "src/net/index.tsx",
      "src/net/sitekit.tsx",
      "src/net/storage.ts",
      "src/net/types.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx",
      "src/shell/ContextMenu.tsx"
    ]
  },
  {
    "id": "mixtinstall",
    "name": "Software Manager",
    "summary": "Package Manager",
    "description": "Install and remove applications",
    "file": "src/apps/software.tsx",
    "categories": [
      "System",
      "Administration"
    ],
    "keywords": [
      "install",
      "apps",
      "packages",
      "apt",
      "store"
    ],
    "dependencies": [
      "react",
      "src/apps/registry.tsx",
      "src/apps/versions.ts",
      "src/os/api.ts",
      "src/os/bus.ts",
      "src/os/storage.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "settings",
    "name": "System Settings",
    "summary": "",
    "description": "Configure appearance, panel, desktop and hardware",
    "file": "src/apps/settings.tsx",
    "categories": [
      "System",
      "Preferences",
      "Administration"
    ],
    "keywords": [
      "control centre",
      "config",
      "theme",
      "wallpaper",
      "display"
    ],
    "dependencies": [
      "react",
      "src/apps/files.tsx",
      "src/apps/registry.tsx",
      "src/os/api.ts",
      "src/os/backup.ts",
      "src/os/bus.ts",
      "src/os/storage.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "xed",
    "name": "Text Editor",
    "summary": "Text Editor",
    "description": "Write documents, notes and code",
    "file": "src/apps/texteditor.tsx",
    "categories": [
      "Accessories"
    ],
    "keywords": [
      "xed",
      "gedit",
      "notepad",
      "editor",
      "write"
    ],
    "dependencies": [
      "react",
      "src/apps/files.tsx",
      "src/os/bus.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "calculator",
    "name": "Calculator",
    "summary": "",
    "description": "Solve everyday maths, with history and programmer mode",
    "file": "src/apps/calculator.tsx",
    "categories": [
      "Accessories"
    ],
    "keywords": [
      "math",
      "sum",
      "numbers",
      "mixt-calculator"
    ],
    "dependencies": [
      "react",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "system-monitor",
    "name": "System Monitor",
    "summary": "",
    "description": "Watch processes, CPU, memory and network usage",
    "file": "src/apps/system-monitor.tsx",
    "categories": [
      "System",
      "Administration"
    ],
    "keywords": [
      "tasks",
      "processes",
      "top",
      "htop",
      "performance"
    ],
    "dependencies": [
      "react",
      "src/apps/registry.tsx",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "mixtplayer",
    "name": "Mixt Player",
    "summary": "Media Player",
    "description": "Play the music and videos in your home folder",
    "file": "src/apps/mixtplayer.tsx",
    "categories": [
      "Sound & Video"
    ],
    "keywords": [
      "music",
      "player",
      "audio",
      "video",
      "media",
      "mp3"
    ],
    "dependencies": [
      "react",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "mediaplayer",
    "name": "VLC media player",
    "summary": "Media Player",
    "description": "Play music and video from your library",
    "file": "src/apps/mediaplayer.tsx",
    "categories": [
      "Sound & Video"
    ],
    "keywords": [
      "vlc",
      "music",
      "player",
      "audio",
      "video",
      "mp3"
    ],
    "dependencies": [
      "react",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "imageviewer",
    "name": "Image Viewer",
    "summary": "Image Viewer",
    "description": "Look at pictures with zoom and rotation",
    "file": "src/apps/imageviewer.tsx",
    "categories": [
      "Graphics"
    ],
    "keywords": [
      "xviewer",
      "photos",
      "pictures",
      "jpeg",
      "png"
    ],
    "dependencies": [
      "react",
      "src/os/bus.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "weather",
    "name": "Weather",
    "summary": "",
    "description": "Forecasts for cities around the world, straight from MixtNet",
    "file": "src/apps/weather.tsx",
    "categories": [
      "Internet",
      "Accessories"
    ],
    "keywords": [
      "forecast",
      "temperature",
      "rain",
      "climate"
    ],
    "dependencies": [
      "react",
      "src/os/bus.ts",
      "src/os/types.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "archive",
    "name": "Archive Manager",
    "summary": "Archive Manager",
    "description": "Create and extract .zip and .tar archives",
    "file": "src/apps/archive.tsx",
    "categories": [
      "Accessories",
      "System"
    ],
    "keywords": [
      "zip",
      "tar",
      "compress",
      "extract",
      "file-roller"
    ],
    "dependencies": [
      "react",
      "src/os/bus.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "screenshot",
    "name": "Screenshot",
    "summary": "",
    "description": "Grab the screen, a window or the desktop background",
    "file": "src/apps/screenshot.tsx",
    "categories": [
      "Accessories",
      "Graphics"
    ],
    "keywords": [
      "capture",
      "grab",
      "png",
      "print screen"
    ],
    "dependencies": [
      "react",
      "src/apps/screenshot-utils.ts",
      "src/os/bus.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "help",
    "name": "Help",
    "summary": "Help & Documentation",
    "description": "A guided tour of Mixt Web OS",
    "file": "src/apps/help.tsx",
    "categories": [
      "Accessories",
      "System"
    ],
    "keywords": [
      "welcome",
      "guide",
      "docs",
      "manual",
      "help"
    ],
    "dependencies": [
      "react",
      "src/net/index.tsx",
      "src/os/bus.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "about",
    "name": "About This Computer",
    "summary": "",
    "description": "System information, hardware and thanks",
    "file": "src/apps/about.tsx",
    "categories": [
      "System",
      "Preferences"
    ],
    "keywords": [
      "neofetch",
      "system info",
      "specs",
      "version"
    ],
    "dependencies": [
      "react",
      "src/apps/registry.tsx",
      "src/os/bus.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "paint",
    "name": "Drawing",
    "summary": "Drawing",
    "description": "Paint with brushes, shapes and text",
    "file": "src/apps/paint.tsx",
    "categories": [
      "Graphics"
    ],
    "keywords": [
      "paint",
      "draw",
      "sketch",
      "canvas"
    ],
    "dependencies": [
      "react",
      "src/apps/files.tsx",
      "src/os/bus.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "mail",
    "name": "Mail",
    "summary": "Email Client",
    "description": "Read and write mail through MixtMail",
    "file": "src/apps/mail.tsx",
    "categories": [
      "Internet"
    ],
    "keywords": [
      "email",
      "inbox",
      "thunderbird"
    ],
    "dependencies": [
      "react",
      "src/apps/mailstore.ts",
      "src/os/api.ts",
      "src/os/bus.ts",
      "src/os/mailaddr.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "news",
    "name": "News Reader",
    "summary": "News Reader",
    "description": "Follow MixtNet news feeds offline",
    "file": "src/apps/news.tsx",
    "categories": [
      "Internet"
    ],
    "keywords": [
      "rss",
      "feeds",
      "headlines",
      "articles"
    ],
    "dependencies": [
      "react",
      "src/os/bus.ts",
      "src/os/storage.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/os/vfs.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "screenviewer",
    "name": "Screen Viewer",
    "summary": "Session Viewer",
    "description": "See what another account or a guest has open",
    "file": "src/apps/screenviewer.tsx",
    "categories": [
      "Administration"
    ],
    "keywords": [
      "screen",
      "session",
      "view",
      "admin",
      "monitor",
      "guests"
    ],
    "dependencies": [
      "react",
      "src/apps/registry.tsx",
      "src/os/api.ts",
      "src/os/store.ts",
      "src/os/types.ts",
      "src/shell/AppIcon.tsx"
    ]
  },
  {
    "id": "administration",
    "name": "Administration",
    "summary": "Administrator Console",
    "description": "Approve published apps, manage whitelisted accounts and inspect the server",
    "file": "src/apps/admin.tsx",
    "categories": [
      "Administration",
      "System"
    ],
    "keywords": [
      "admin",
      "administrator",
      "approve",
      "users",
      "server",
      "root",
      "privileged"
    ],
    "dependencies": [
      "react",
      "src/os/api.ts",
      "src/os/mailaddr.ts",
      "src/os/types.ts"
    ]
  }
]

/** files in src/apps that belong to no registered app (shared helpers) */
export const APP_SHARED_FILES: string[] = [
  "src/apps/mailstore.ts",
  "src/apps/registry.tsx",
  "src/apps/screenshot-utils.ts",
  "src/apps/versions.ts"
]
