/* Generated by scripts/gen-defaultfs.mjs from the defaultfs/ folder at the
 * root of the repository. Do not edit by hand — edit the files there and run
 * `npm run gen:defaultfs` (or `npm run build`, which runs it for you).
 *
 * This is the filesystem every new account and every guest starts with:
 * 24 files in 29 directories, read straight off disk so it can be
 * read and changed like any other part of the repository. It is compiled into
 * the bundle, so the desktop needs no network to produce it.
 */
export interface DefaultNode {
  type: 'dir' | 'file'
  children?: Record<string, DefaultNode>
  content?: string
  mime?: string
}

export const DEFAULT_FILESYSTEM: Record<string, DefaultNode> = {
  "etc": {
    "type": "dir",
    "children": {
      "hostname": {
        "type": "file",
        "content": "mixt-web\n"
      },
      "hosts": {
        "type": "file",
        "content": "# /etc/hosts — static table lookup for hostnames.\n# Entries here are checked before MixtNet DNS, exactly like a real resolver.\n127.0.0.1       localhost\n127.0.1.1       mixt-web\n::1             localhost ip6-localhost ip6-loopback\n10.0.0.53       ns1.mixtnet.com dns1\n10.0.0.54       ns2.mixtnet.com dns2\n\n# Add your own names below, e.g.\n# 10.99.0.1     my-server.lan\n"
      },
      "machine-id": {
        "type": "file",
        "content": "f3d0c1a2b4e5968790a1b2c3d4e5f607\n"
      },
      "os-release": {
        "type": "file",
        "content": "NAME=\"Mixt Web OS\"\nVERSION=\"1.0 (Mixty)\"\nID=mixtwebos\nID_LIKE=mixtos\nPRETTY_NAME=\"Mixt Web OS 1.0\"\nVERSION_ID=\"1.0\"\nHOME_URL=\"https://mixt.local/\"\nSUPPORT_URL=\"https://mixt.local/help\"\nBUG_REPORT=\"https://mixt.local/bugs\"\n"
      },
      "passwd": {
        "type": "file",
        "content": "root:x:0:0:root:/root:/bin/bash\nmixt:x:1000:1000:Mixt User:/home/mixt:/bin/bash\nnobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin\n"
      },
      "resolv.conf": {
        "type": "file",
        "content": "# Generated by MixtNet NetworkManager.\nnameserver 10.0.0.53\nnameserver 10.0.0.54\nsearch mixtnet\noptions timeout:1 attempts:2\n"
      },
      "shells": {
        "type": "file",
        "content": "/bin/sh\n/bin/bash\n/bin/dash\n"
      }
    }
  },
  "home": {
    "type": "dir",
    "children": {
      "mixt": {
        "type": "dir",
        "children": {
          ".bashrc": {
            "type": "file",
            "content": "# ~/.bashrc — sourced by interactive bash shells\nPS1=\"\\u@\\h \\w \\$ \"\nalias ll=\"ls -la\"\nalias ..=\"cd ..\"\n"
          },
          ".config": {
            "type": "dir",
            "children": {
              "mixt-web-os.conf": {
                "type": "file",
                "content": "[desktop]\nwallpaper=wallpapers/mixt-wave.jpg\nscheme=light\n\n[panel]\nposition=bottom\nsize=40\n"
              },
              "user-dirs.dirs": {
                "type": "file",
                "content": "XDG_DESKTOP_DIR=\"$HOME/Desktop\"\nXDG_DOWNLOAD_DIR=\"$HOME/Downloads\"\nXDG_TEMPLATES_DIR=\"$HOME/Templates\"\nXDG_PUBLICSHARE_DIR=\"$HOME/Public\"\nXDG_DOCUMENTS_DIR=\"$HOME/Documents\"\nXDG_MUSIC_DIR=\"$HOME/Music\"\nXDG_PICTURES_DIR=\"$HOME/Pictures\"\nXDG_VIDEOS_DIR=\"$HOME/Videos\"\n"
              }
            }
          },
          ".local": {
            "type": "dir",
            "children": {
              "share": {
                "type": "dir",
                "children": {
                  "Trash": {
                    "type": "dir",
                    "children": {
                      "files": {
                        "type": "dir",
                        "children": {}
                      },
                      "info": {
                        "type": "dir",
                        "children": {}
                      }
                    }
                  },
                  "recently-used.xbel": {
                    "type": "file",
                    "content": "<?xml version=\"1.0\"?><xbel version=\"1.0\"/>"
                  }
                }
              }
            }
          },
          ".profile": {
            "type": "file",
            "content": "export PATH=\"$HOME/bin:$PATH\"\nexport EDITOR=xed\n"
          },
          "Desktop": {
            "type": "dir",
            "children": {
              "welcome.txt": {
                "type": "file",
                "content": "Welcome to Mixt Web OS!\n\nTry the Menu (bottom left), open a Terminal and type \"neofetch\".\n"
              }
            }
          },
          "Documents": {
            "type": "dir",
            "children": {
              "recipe-mixt-lemonade.md": {
                "type": "file",
                "content": "# Mixt lemonade\n\n- 2 limes\n- 1 lemon\n- 8 fresh mixt leaves\n- 60 g sugar\n- 1 l sparkling water\n\nMuddle mixt with sugar, add citrus juice, top with sparkling water and ice.\n",
                "mime": "text/markdown"
              },
              "todo.txt": {
                "type": "file",
                "content": "[x] Boot Mixt Web OS\n[ ] Try the terminal\n[ ] Rearrange the panel applets\n[ ] Install Photo Studio from the Software Manager\n[ ] Write a website and visit it in the browser\n"
              },
              "welcome.md": {
                "type": "file",
                "content": "# Welcome to Mixt Web OS\n\nYou are looking at a complete desktop, running entirely in your browser.\n\n## Things to try\n1. **Menu ▸ Web Browser** — browse the built-in *MixtNet* internet, or real websites.\n2. **Menu ▸ Terminal** — type `neofetch`, `ls`, `help`.\n3. **Menu ▸ Software Manager** — install extra apps like Photo Studio.\n4. Drag windows, snap them to screen edges, switch workspaces in the panel.\n5. Right-click the desktop to change the background.\n\nEverything you create is saved in your browser and survives a reboot.\n",
                "mime": "text/markdown"
              }
            }
          },
          "Downloads": {
            "type": "dir",
            "children": {}
          },
          "Music": {
            "type": "dir",
            "children": {
              "Mixt Dreams.ogg": {
                "type": "file",
                "content": "{\"kind\": \"synth\", \"bpm\": 78, \"key\": \"D\", \"pattern\": [\"D3\", \"F3\", \"A3\", \"C4\", \"A3\", \"F3\"], \"wave\": \"triangle\", \"artist\": \"Mixt Sound System\"}",
                "mime": "audio/ogg"
              },
              "Mixty Fresh Waves.ogg": {
                "type": "file",
                "content": "{\"kind\": \"synth\", \"bpm\": 96, \"key\": \"A\", \"pattern\": [\"A3\", \"C4\", \"E4\", \"G4\", \"E4\", \"C4\"], \"wave\": \"sine\", \"artist\": \"Mixt Sound System\"}",
                "mime": "audio/ogg"
              },
              "Terminal Velocity.ogg": {
                "type": "file",
                "content": "{\"kind\": \"synth\", \"bpm\": 132, \"key\": \"E\", \"pattern\": [\"E3\", \"B3\", \"E4\", \"G4\", \"B4\", \"G4\"], \"wave\": \"sawtooth\", \"artist\": \"Mixt Sound System\"}",
                "mime": "audio/ogg"
              }
            }
          },
          "Pictures": {
            "type": "dir",
            "children": {
              "Wallpapers": {
                "type": "dir",
                "children": {}
              }
            }
          },
          "Public": {
            "type": "dir",
            "children": {}
          },
          "Templates": {
            "type": "dir",
            "children": {
              "Empty Document.txt": {
                "type": "file",
                "content": ""
              }
            }
          },
          "Videos": {
            "type": "dir",
            "children": {
              "Mixt Intro.webm": {
                "type": "file",
                "content": "{\"kind\": \"animation\", \"title\": \"Mixt Intro\", \"seconds\": 12}",
                "mime": "video/webm"
              }
            }
          }
        }
      }
    }
  },
  "usr": {
    "type": "dir",
    "children": {
      "local": {
        "type": "dir",
        "children": {
          "bin": {
            "type": "dir",
            "children": {}
          }
        }
      },
      "share": {
        "type": "dir",
        "children": {
          "backgrounds": {
            "type": "dir",
            "children": {}
          },
          "doc": {
            "type": "dir",
            "children": {
              "mixt-web-os": {
                "type": "dir",
                "children": {
                  "README.txt": {
                    "type": "file",
                    "content": "Mixt Web OS 1.0 — a whole desktop computer inside a web page.\n\nMixt Web OS boots a window manager, a panel, a virtual filesystem, a\nterminal, a file manager, a software store and a web browser — all\nclient-side, no server required.\n\nKeyboard shortcuts\n  Super                open the menu\n  Alt+Tab              switch windows\n  Ctrl+Alt+T           open a terminal\n  Ctrl+Alt+Left/Right  switch workspaces\n  Super+D              show the desktop\n  Alt+F2               run a command\n\nThe whole filesystem lives in your browser's localStorage at\n/home/mixt/ — poke around, nothing breaks.\n"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "var": {
    "type": "dir",
    "children": {
      "cache": {
        "type": "dir",
        "children": {}
      },
      "log": {
        "type": "dir",
        "children": {
          "boot.log": {
            "type": "file",
            "content": "[    0.000000] Mixt Web OS 1.0 (mixt) booting on JavaScript kernel\n[    0.012884] cpu: 2 virtual cores detected\n[    0.104331] memory: 3.9 GiB available\n[    0.402117] vfs: mounted local filesystem at /\n[    0.611003] wm: Mixt Shell window manager ready\n[    0.883440] panel: applets loaded (menu, windows, tray, clock)\n[    1.002991] browser: mixtnet resolver online\n[    1.201554] init: Reached target Graphical Interface\n"
          },
          "mixtinstall.log": {
            "type": "file",
            "content": "2026-09-30 09:12:44 install mixt-shell:all <none> 1.0\n2026-09-30 09:12:44 status half-installed mixt-shell:all 1.0\n2026-09-30 09:12:45 status installed mixt-shell:all 1.0\n"
          }
        }
      },
      "tmp": {
        "type": "dir",
        "children": {}
      }
    }
  }
}

export const DEFAULT_FILE_COUNT = 24
export const DEFAULT_DIR_COUNT = 29
