/* Mint Web OS — virtual filesystem (ext4-ish, lives in localStorage)
   Everything inside the OS reads and writes through this module. */
import { create } from 'zustand'

export interface VFileNode {
  type: 'file'
  content: string
  mime?: string
  /** external url (images/wallpapers) instead of inline content */
  url?: string
  created: number
  modified: number
}
export interface VDirNode {
  type: 'dir'
  children: Record<string, VNode>
  created: number
  modified: number
}
export type VNode = VFileNode | VDirNode

const LS_KEY = 'webmpl.vfs.v2'
const now = () => Date.now()

export function file(content: string, mime = 'text/plain', url?: string): VFileNode {
  return { type: 'file', content, mime, url, created: now(), modified: now() }
}
export function dir(children: Record<string, VNode> = {}): VDirNode {
  return { type: 'dir', children, created: now(), modified: now() }
}

/* ------------------------------- path utils ------------------------------- */
export function normalizeHome(p: string, home: string) {
  if (!p) return home
  if (p === '~') return home
  if (p.startsWith('~/')) return home + p.slice(1)
  return p
}

export function normalizePath(p: string, cwd: string, home: string): string {
  let path = normalizeHome(p.trim(), home)
  if (!path.startsWith('/')) path = join(cwd, path)
  const parts: string[] = []
  for (const seg of path.split('/')) {
    if (!seg || seg === '.') continue
    if (seg === '..') parts.pop()
    else parts.push(seg)
  }
  return '/' + parts.join('/')
}

export function join(...parts: string[]) {
  return parts
    .filter(Boolean)
    .join('/')
    .replace(/\/+/g, '/')
    .replace(/\/$/, '') || '/'
}

export function parentPath(p: string) {
  if (p === '/') return '/'
  return p.replace(/\/[^/]*$/, '') || '/'
}

export function baseName(p: string) {
  if (p === '/') return '/'
  return p.replace(/\/+$/, '').split('/').pop() || '/'
}

export function splitPath(p: string) {
  return p.split('/').filter(Boolean)
}

export function humanSize(n: number) {
  if (n < 1000) return `${n} bytes`
  const units = ['kB', 'MB', 'GB', 'TB']
  let v = n / 1000
  let i = 0
  while (v >= 1000 && i < units.length - 1) {
    v /= 1000
    i++
  }
  return `${v.toFixed(v < 10 ? 1 : 0)} ${units[i]}`
}

export function nodeSize(n: VNode): number {
  if (n.type === 'file') return (n.url ? 240_000 : 0) + (n.content?.length ?? 0)
  return Object.values(n.children).reduce((a, c) => a + nodeSize(c), 0)
}

export function countNodes(n: VNode): number {
  if (n.type === 'file') return 1
  return Object.values(n.children).reduce((a, c) => a + countNodes(c), 0)
}

/* --------------------------------- seeds --------------------------------- */
const WALLPAPERS = ['mint-wave.jpg', 'mint-facets.jpg', 'mint-leaf.jpg']

function seedTree(): VDirNode {
  const wallChildren: Record<string, VNode> = {}
  for (const w of WALLPAPERS) {
    wallChildren[w] = {
      type: 'file',
      content: '',
      mime: 'image/jpeg',
      url: `/wallpapers/${w}`,
      created: now(),
      modified: now(),
    }
  }

  return dir({
    etc: dir({
      'os-release': file(
        `NAME="Mint Web OS"\nVERSION="1.0 (Minty)"\nID=mintwebos\nID_LIKE=linuxmint ubuntu debian\nPRETTY_NAME="Mint Web OS 1.0"\nVERSION_ID="1.0"\nHOME_URL="https://webmpl.local/"\nSUPPORT_URL="https://webmpl.local/help"\nBUG_REPORT_URL="https://webmpl.local/bugs"\nUBUNTU_CODENAME=jammy\n`,
      ),
      hostname: file('mint-web\n'),
      shells: file('/bin/sh\n/bin/bash\n/bin/dash\n'),
      'resolv.conf': file(
        '# Generated by MintNet NetworkManager.\nnameserver 10.0.0.53\nnameserver 10.0.0.54\nsearch mintnet\noptions timeout:1 attempts:2\n',
      ),
      hosts: file(
        '# /etc/hosts — static table lookup for hostnames.\n# Entries here are checked before MintNet DNS, exactly like a real resolver.\n127.0.0.1       localhost\n127.0.1.1       mint-web\n::1             localhost ip6-localhost ip6-loopback\n10.0.0.53       ns1.mintnet.com dns1\n10.0.0.54       ns2.mintnet.com dns2\n\n# Add your own names below, e.g.\n# 10.99.0.1     my-server.lan\n',
      ),
      passwd: file(
        'root:x:0:0:root:/root:/bin/bash\nmint:x:1000:1000:Mint User:/home/mint:/bin/bash\nnobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin\n',
      ),
      'machine-id': file('f3d0c1a2b4e5968790a1b2c3d4e5f607\n'),
    }),
    usr: dir({
      share: dir({
        backgrounds: dir(wallChildren),
        doc: dir({
          'mint-web-os': dir({
            'README.txt': file(
              `Mint Web OS 1.0 — a whole desktop computer inside a web page.

Mint Web OS boots a window manager, a panel, a virtual filesystem, a
terminal, a file manager, a software store and a web browser — all
client-side, no server required.

Keyboard shortcuts
  Super                open the menu
  Alt+Tab              switch windows
  Ctrl+Alt+T           open a terminal
  Ctrl+Alt+Left/Right  switch workspaces
  Super+D              show the desktop
  Alt+F2               run a command

The whole filesystem lives in your browser's localStorage at
/home/${'mint'}/ — poke around, nothing breaks.
`,
            ),
          }),
        }),
        applications: dir({}),
      }),
      local: dir({ bin: dir({}) }),
    }),
    var: dir({
      log: dir({
        'boot.log': file(
          `[    0.000000] Mint Web OS 1.0 (webmpl) booting on JavaScript kernel\n[    0.012884] cpu: 2 virtual cores detected\n[    0.104331] memory: 3.9 GiB available\n[    0.402117] vfs: mounted local filesystem at /\n[    0.611003] wm: Cinnamon-compatible window manager ready\n[    0.883440] panel: applets loaded (menu, windows, tray, clock)\n[    1.002991] browser: mintnet resolver online\n[    1.201554] systemd: Reached target Graphical Interface\n`,
        ),
        'dpkg.log': file('2026-09-30 09:12:44 install webmpl-shell:all <none> 1.0\n2026-09-30 09:12:44 status half-installed webmpl-shell:all 1.0\n2026-09-30 09:12:45 status installed webmpl-shell:all 1.0\n'),
      }),
      cache: dir({}),
      tmp: dir({}),
    }),
    home: dir({
      mint: dir({
        Desktop: dir({
          'welcome.txt': file(
            'Welcome to Mint Web OS!\n\nTry the Menu (bottom left), open a Terminal and type "neofetch".\n',
          ),
        }),
        Documents: dir({
          'welcome.md': file(
            `# Welcome to Mint Web OS

You are looking at a complete desktop, running entirely in your browser.

## Things to try
1. **Menu ▸ Web Browser** — browse the built-in *MintNet* internet, or real websites.
2. **Menu ▸ Terminal** — type \`neofetch\`, \`ls\`, \`help\`.
3. **Menu ▸ Software Manager** — install extra apps like Photo Studio.
4. Drag windows, snap them to screen edges, switch workspaces in the panel.
5. Right-click the desktop to change the background.

Everything you create is saved in your browser and survives a reboot.
`,
          ),
          'todo.txt': file(
            '[x] Boot Mint Web OS\n[ ] Try the terminal\n[ ] Rearrange the panel applets\n[ ] Install Photo Studio from the Software Manager\n[ ] Write a website and visit it in the browser\n',
          ),
          'recipe-mint-lemonade.md': file(
            '# Mint lemonade\n\n- 2 limes\n- 1 lemon\n- 8 fresh mint leaves\n- 60 g sugar\n- 1 l sparkling water\n\nMuddle mint with sugar, add citrus juice, top with sparkling water and ice.\n',
          ),
        }),
        Downloads: dir({
          'README.txt': file(
            'Downloads from the MintNet browser end up here.\n',
          ),
          'mint-wallpapers.zip': file('PK\u0003\u0004 (fake archive placeholder)\n', 'application/zip'),
          'firefox-129.0.tar.bz2': file('BZh9 fake tarball placeholder\n', 'application/x-bzip2'),
        }),
        Music: dir({
          'Minty Fresh Waves.ogg': file(
            JSON.stringify({
              kind: 'synth',
              bpm: 96,
              key: 'A',
              pattern: ['A3', 'C4', 'E4', 'G4', 'E4', 'C4'],
              wave: 'sine',
              artist: 'WebMpl Sound System',
            }),
            'audio/ogg',
          ),
          'Cinnamon Dreams.ogg': file(
            JSON.stringify({
              kind: 'synth',
              bpm: 78,
              key: 'D',
              pattern: ['D3', 'F3', 'A3', 'C4', 'A3', 'F3'],
              wave: 'triangle',
              artist: 'WebMpl Sound System',
            }),
            'audio/ogg',
          ),
          'Terminal Velocity.ogg': file(
            JSON.stringify({
              kind: 'synth',
              bpm: 132,
              key: 'E',
              pattern: ['E3', 'B3', 'E4', 'G4', 'B4', 'G4'],
              wave: 'sawtooth',
              artist: 'WebMpl Sound System',
            }),
            'audio/ogg',
          ),
        }),
        Pictures: dir({ Wallpapers: dir(wallChildren) }),
        Videos: dir({
          'Mint Intro.webm': file(
            JSON.stringify({ kind: 'animation', title: 'Mint Intro', seconds: 12 }),
            'video/webm',
          ),
        }),
        Public: dir({}),
        Templates: dir({
          'Empty Document.txt': file(''),
        }),
        '.config': dir({
          'user-dirs.dirs': file(
            'XDG_DESKTOP_DIR="$HOME/Desktop"\nXDG_DOWNLOAD_DIR="$HOME/Downloads"\nXDG_TEMPLATES_DIR="$HOME/Templates"\nXDG_PUBLICSHARE_DIR="$HOME/Public"\nXDG_DOCUMENTS_DIR="$HOME/Documents"\nXDG_MUSIC_DIR="$HOME/Music"\nXDG_PICTURES_DIR="$HOME/Pictures"\nXDG_VIDEOS_DIR="$HOME/Videos"\n',
          ),
          'mint-web-os.conf': file(
            '[desktop]\nwallpaper=/wallpapers/mint-wave.jpg\nscheme=light\n\n[panel]\nposition=bottom\nsize=40\n',
          ),
        }),
        '.bashrc': file(
          '# ~/.bashrc — sourced by interactive bash shells\nPS1="\\u@\\h \\w \\$ "\nalias ll="ls -la"\nalias ..="cd .."\n',
        ),
        '.profile': file('export PATH="$HOME/bin:$PATH"\nexport EDITOR=xed\n'),
        '.local': dir({
          share: dir({
            Trash: dir({ files: dir({}), info: dir({}) }),
            'recently-used.xbel': file('<?xml version="1.0"?><xbel version="1.0"/>'),
          }),
        }),
      }),
    }),
    bin: dir({
      bash: file('<binary>', 'application/x-executable'),
      ls: file('<binary>', 'application/x-executable'),
      nemo: file('<binary>', 'application/x-executable'),
      xed: file('<binary>', 'application/x-executable'),
    }),
  })
}

/* --------------------------------- state --------------------------------- */
interface VFSState {
  root: VDirNode
  revision: number
  /** mount points for pseudo filesystems (kept out of localStorage) */
  getNode: (path: string) => VNode | null
  list: (path: string) => { name: string; node: VNode }[] | null
  mkdir: (path: string) => boolean
  writeFile: (path: string, content: string, mime?: string, url?: string) => boolean
  touch: (path: string) => boolean
  remove: (path: string) => boolean
  move: (from: string, to: string) => boolean
  copy: (from: string, to: string) => boolean
  exists: (path: string) => boolean
  reset: () => void
  persist: () => void
}

function loadRoot(): VDirNode {
  try {
    const raw = localStorage.getItem(LS_KEY)
    if (raw) {
      const parsed = JSON.parse(raw)
      if (parsed && parsed.type === 'dir') return parsed as VDirNode
    }
  } catch {
    /* corrupted store — start fresh */
  }
  return seedTree()
}

let persistTimer: any = null
function schedulePersist(get: () => VFSState) {
  clearTimeout(persistTimer)
  persistTimer = setTimeout(() => {
    try {
      localStorage.setItem(LS_KEY, JSON.stringify(get().root))
    } catch {
      /* quota exceeded — ignore */
    }
  }, 350)
}

export const useVFS = create<VFSState>()((set, get) => ({
  root: loadRoot(),
  revision: 0,

  getNode: (path) => {
    if (path === '/' || path === '') return get().root
    let node: VNode = get().root
    for (const seg of splitPath(path)) {
      if (node.type !== 'dir') return null
      const next = node.children[seg]
      if (!next) return null
      node = next
    }
    return node
  },

  list: (path) => {
    const node = get().getNode(path)
    if (!node || node.type !== 'dir') return null
    return Object.entries(node.children)
      .map(([name, n]) => ({ name, node: n }))
      .sort((a, b) => {
        if (a.node.type !== b.node.type) return a.node.type === 'dir' ? -1 : 1
        return a.name.localeCompare(b.name, undefined, { numeric: true })
      })
  },

  mkdir: (path) => {
    const parent = parentPath(path)
    const name = baseName(path)
    const p = get().getNode(parent)
    if (!p || p.type !== 'dir' || p.children[name]) return false
    p.children[name] = dir({})
    p.modified = now()
    set((s) => ({ revision: s.revision + 1 }))
    schedulePersist(get)
    return true
  },

  writeFile: (path, content, mime = 'text/plain', url) => {
    const parent = parentPath(path)
    const name = baseName(path)
    const p = get().getNode(parent)
    if (!p || p.type !== 'dir') return false
    const existing = p.children[name]
    if (existing && existing.type === 'dir') return false
    if (existing && existing.type === 'file') {
      existing.content = content
      existing.mime = mime
      if (url !== undefined) existing.url = url
      existing.modified = now()
    } else {
      p.children[name] = { type: 'file', content, mime, url, created: now(), modified: now() }
    }
    p.modified = now()
    set((s) => ({ revision: s.revision + 1 }))
    schedulePersist(get)
    return true
  },

  touch: (path) => {
    const parent = parentPath(path)
    const name = baseName(path)
    const p = get().getNode(parent)
    if (!p || p.type !== 'dir') return false
    if (!p.children[name]) {
      p.children[name] = file('')
      set((s) => ({ revision: s.revision + 1 }))
      schedulePersist(get)
    }
    return true
  },

  remove: (path) => {
    const p = get().getNode(parentPath(path))
    const name = baseName(path)
    if (!p || p.type !== 'dir' || !p.children[name]) return false
    delete p.children[name]
    p.modified = now()
    set((s) => ({ revision: s.revision + 1 }))
    schedulePersist(get)
    return true
  },

  move: (from, to) => {
    const srcParent = get().getNode(parentPath(from))
    const node = get().getNode(from)
    if (!node || !srcParent || srcParent.type !== 'dir') return false
    let destPath = to
    if (get().exists(to) && get().getNode(to)?.type === 'dir') {
      destPath = join(to, baseName(from))
    }
    const dstParent = get().getNode(parentPath(destPath))
    if (!dstParent || dstParent.type !== 'dir') return false
    delete srcParent.children[baseName(from)]
    dstParent.children[baseName(destPath)] = node
    node.modified = now()
    set((s) => ({ revision: s.revision + 1 }))
    schedulePersist(get)
    return true
  },

  copy: (from, to) => {
    const node = get().getNode(from)
    if (!node) return false
    let destPath = to
    if (get().getNode(to)?.type === 'dir') destPath = join(to, baseName(from))
    const dstParent = get().getNode(parentPath(destPath))
    if (!dstParent || dstParent.type !== 'dir') return false
    dstParent.children[baseName(destPath)] = JSON.parse(JSON.stringify(node))
    set((s) => ({ revision: s.revision + 1 }))
    schedulePersist(get)
    return true
  },

  exists: (path) => !!get().getNode(path),

  reset: () => {
    const root = seedTree()
    set((s) => ({ root, revision: s.revision + 1 }))
    try {
      localStorage.setItem(LS_KEY, JSON.stringify(root))
    } catch {
      /* ignore */
    }
  },

  persist: () => schedulePersist(get),
}))

/** home directory of the session user */
export const HOME = '/home/mint'
export const TRASH_DIR = '/home/mint/.local/share/Trash/files'

/** imperative helpers usable outside React */
export const vfs = {
  node: (p: string) => useVFS.getState().getNode(p),
  list: (p: string) => useVFS.getState().list(p),
  read: (p: string) => {
    const n = useVFS.getState().getNode(p)
    if (!n || n.type !== 'file') return null
    return n.content
  },
  write: (p: string, c: string, mime?: string, url?: string) =>
    useVFS.getState().writeFile(p, c, mime, url),
  mkdir: (p: string) => useVFS.getState().mkdir(p),
  mkdirp: (p: string) => {
    const parts = splitPath(p)
    let cur = ''
    for (const part of parts) {
      cur = join(cur, part)
      if (!useVFS.getState().exists(cur)) useVFS.getState().mkdir(cur)
    }
    return true
  },
  rm: (p: string) => useVFS.getState().remove(p),
  mv: (a: string, b: string) => useVFS.getState().move(a, b),
  cp: (a: string, b: string) => useVFS.getState().copy(a, b),
  exists: (p: string) => useVFS.getState().exists(p),
  trash: (p: string) => {
    vfs.mkdirp('/home/mint/.local/share/Trash/info')
    const name = baseName(p)
    const stamp = new Date().toISOString()
    useVFS.getState().writeFile(
      join('/home/mint/.local/share/Trash/info', `${name}.trashinfo`),
      `[Trash Info]\nPath=${p}\nDeletionDate=${stamp}\n`,
    )
    return useVFS.getState().move(p, join(TRASH_DIR, name))
  },
  reset: () => useVFS.getState().reset(),
}
