/* Generated by scripts/gen-defaultfs.mjs from wallpapers/index.json. Do not
 * edit by hand: add a background to the folder and list it there.
 *
 * The order the backgrounds are offered in, so that the picker in Settings and
 * `wallpaper <n>` in the terminal number them the same way. The server seeds
 * every new account's /usr/share/backgrounds from this same list. */
export const WALLPAPERS: string[] = [
  "mixt-wave.jpg",
  "mixt-facets.jpg",
  "mixt-leaf.jpg"
]
